[package]
name = "asi_vulkan"
version = "0.9.1"
license = "MIT / BSL-1.0"
documentation = "https://docs.rs/asi_vulkan"
homepage = "https://github.com/AldaronLau/asi_vulkan"
repository = "https://github.com/AldaronLau/asi_vulkan"
readme = "README.md"
description = "Rust safe bindings for Vulkan."
keywords = ["vulkan"]
categories = [
    "api-bindings",
    "external-ffi-bindings",
    "hardware-support",
    "rendering",
    "rendering::graphics-api",
]

[badges.maintenance]
status = "deprecated"

[dependencies]
dl_api = "0.2"
awi = "0.8"
euler = "0.4"

[features]
default = [] # ["checks"] # Un-comment for validation layers.
checks = []
